### PR TITLE
Feature/ci cd

### LINKED ISSUE #5: [DEV] Add CI/CD
See BUILD.md for instructions

### PR DESCRIPTION
**Pull request by Riernar**
- Requires #3 
- Fix #5

### CODE REVIEW

**Comment by Riernar** [comment]
@Kurohyou 
Looks like the `passhandle` branch is not functional: even on local, `npm run build` fails.
Could you fix the `passhandle` branch so that I can rebase this PR on it ?

**Comment by Kurohyou** [comment]
CI/CD action is updated so that all actions run successfully except for the push action.

**Comment by Kurohyou** [comment]
Additionally, passhandle branch is now out of date and that PR will be closed.

**Comment by Riernar** [comment]
Looks like you latest commit broke the tests

**Pull request merged**
