### PR TITLE
Added modal window mixins

### PR DESCRIPTION
**Pull request by Riernar**
Added mixins to make modal window, i.e. pop-up, in the sheet. Useful for e.g. settings pages.

### CODE REVIEW

**Comment by Riernar** [comment]
@Kurohyou The tests are failing due to the added SCSS, but I don't really know how to change them. Looks like I need to edit the `__test__/__snapshots__` folder ? Or is that supposed to be generated somehow ?

**Comment by Kurohyou** [comment]
Snapshots are autogenerated. If you run the test `test-watch` command, you can enter `u` after the tests have run (and the generated scss has failed) to update the snapshots. We should also update the pug test files so that this new mixin set is tested along with everything else.

**Comment by Riernar** [comment]
Thanks, I'll update the tests.
No js, this is pure CSS, adapted from https://codepen.io/Idered/pen/DdeoeW, that Chuz linked in the Discord.

**Comment by Riernar** [comment]
@Kurohyou I updated the tests snapshot, and wrote a `test-sheet/source/modal.test.pug` but I don't think it's actually integrated into the tests. Any hint on how to do that ? The `__test__` folder is a bit obscure to me, not knowing how to use vitest (I should probably look at that I guess).

**Comment by Kurohyou** [comment]
The pug testing is a little odd. I really need to put details on how that works in the readme.

Essentially, you just need to include the `test.pug` in the `test_sheet/source/assets/pug/_index.pug` file. This will then include it in the `K-scaffold_Tester.pug` file and then the build will include it in the tester html. The generation tests simply compare the generated html to a snapshot of the html. Eventually I'll make this more granular so that there are discrete tests for each pug mixin, but it works for now.

**Comment by Kurohyou** [comment]
Actually, looking at this more. It'd go in the `test_sheet/source/assets/pug/articles/` directory and be included in `test_sheet/source/assets/pug/articles/_index.pug`.

**Comment by Kurohyou** [comment]
Gonna play with this a bit before I merge it.

**Comment by Kurohyou** [comment]
@Riernar, updated the modal setup to use several variables for easy customization. Also changed positionings so that the modal places itself in the middle of the sheet. Let me know what you think.

**Comment by Riernar** [comment]
I tried with the example sheet, it doesn't seems to work: the CSS is not included with just the `k.defaultStyles` styling.
Am I missing something ?

**Comment by Kurohyou** [comment]
Ah, I'll need to make some tweaks so it can be used within a given position.

**Comment by Kurohyou** [comment]
not sure why it isn't working at all for you though on the test sheet.

**Pull request merged**
